dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
install:
  - npm install -g electron-forge
  - npm install
script:
  - npm test
deploy:
  provider: script
  script: electron-forge publish
  on:
    branch:
      - master
      - travis
