dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
install:
  - npm install -g electron-forge
  - npm install
script:
  - electron-forge pusblish
branches:
  only:
    - master
    - travis
