osx_image: xcode7.3
sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: osx
  - os: linux

install:
  - npm install -g electron-forge
  - npm install
script:
  - electron-forge pusblish
branches:
  only:
    - master
    - travis
