platform:
  - x64

install:
  - ps: Install-Product node 7 x64
  - npm install -g electron-forge
  - npm install
test_script:
  - npm test

build_script:
  - electron-forge publish

branches:
    only:
      - master
      - travis
